#define TALLYBOX_CONFIGURATION_DEFAULT_SSID             "myTallyNetSSID"        /*customize*/
#define TALLYBOX_CONFIGURATION_DEFAULT_PASSWD           "myTallyNetPassword"    /*customize*/

#define TALLYBOX_CONFIGURATION_DEFAULT_HOSTIP_BYTE0     192
#define TALLYBOX_CONFIGURATION_DEFAULT_HOSTIP_BYTE1     168
#define TALLYBOX_CONFIGURATION_DEFAULT_HOSTIP_BYTE2     1
#define TALLYBOX_CONFIGURATION_DEFAULT_HOSTIP_BYTE3     100
